name: Android Application Build Tests

on:
    pull_request:
        branches:
            - "development"

jobs:
    test_ionic:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 18.x

            - name: Install Ionic
              run: npm install -g @ionic/cli

            - name: Install app dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm test.unit

            - name: Run E2E Tests
              run: npm test.e2e
