name: Android Application Build Tests

on:
    pull_request:
        branches:
            - "development"
    push:
        branches:
            - "development"

    workflow_dispatch:

jobs:
    build_android:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup java
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 21.x

            - name: Install Cordova
              run: npm install -g cordova

            - name: Install Ionic
              run: npm install -g @ionic/cli

            - name: Install app dependencies
              run: npm install

            - name: Add Android platform
              run: ionic cordova platform add android@latest

            - name: Build Android Dev APK
              run: ionic cordova build android

            - name: Build Android Release APK
              run: ionic cordova build android --release --prod
