name: Android Application Build Tests

on:
    pull_request:
        branches:
            - "development"
    push:
        branches:
            - "development"
    workflow_dispatch:

jobs:
    build_android:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 21.x

            - name: Install Ionic
              run: npm install -g @ionic/cli

            - name: Install app dependencies
              run: npm install

            - name: Copy web assets to native Android project
              run: npx cap copy android

            - name: Build Android Dev APK
              run: |
                  cd android
                  ./gradlew assembleDebug

            - name: Build Android Release APK
              run: |
                  cd android
                  ./gradlew bundleRelease
