name: Android Application Deployment

on:
    push:
        branches:
            - "production"

jobs:
    release_android:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 18.x

            - name: Install Ionic
              run: npm install -g @ionic/cli

            - name: Install app dependencies
              run: npm install

            - name: Copy web assets to native Android project
              run: npx cap copy android

            - name: Open native Android project in Android Studio
              run: npx cap open android

            - name: Setup Gradle
              uses: gradle/wrapper-validation-action@v3

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Build Android APK
              run: |
                  cd android
                  ./gradlew assembleDebug

            - name: Generate the Android App Bundle
              run: |
                  cd android
                  ./gradlew bundle

            - name: Upload dev APK
              uses: actions/upload-artifact@v2
              with:
                  name: app-dev
                  path: android/app/build/outputs/apk/debug/app-debug.apk

            - name: Upload release bundle
              uses: actions/upload-artifact@v2
              with:
                  name: app-release
                  path: android/app/build/outputs/bundle/release/app.aab
